In [1]:
! pip install gensim


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.8/27.8 MB 58.7 MB/s eta 0:00:00


# ***import pretrained model***

In [2]:
import gensim.downloader as api
model=api.load("word2vec-google-news-300")

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [33]:
vector1=model

In [34]:
print(vector1["person"])

[ 0.27539062 -0.24707031  0.01721191  0.16796875 -0.14550781  0.16015625
  0.16503906  0.12158203  0.16699219 -0.30664062  0.00509644 -0.12158203
  0.11816406 -0.25        0.03857422  0.23046875 -0.1953125   0.00982666
 -0.11132812 -0.09912109 -0.03710938 -0.20019531  0.02600098 -0.26171875
 -0.05224609 -0.16015625 -0.19628906  0.2421875  -0.02441406 -0.08544922
 -0.06494141  0.00588989 -0.27929688  0.10009766 -0.109375    0.17578125
  0.00921631 -0.01696777 -0.14648438  0.17382812 -0.07861328 -0.04443359
  0.11181641  0.14648438  0.18164062 -0.10253906 -0.01171875 -0.0133667
 -0.08544922 -0.1171875  -0.02758789 -0.10400391  0.08447266 -0.0088501
  0.15820312  0.02246094  0.00561523  0.04077148  0.16601562 -0.04858398
  0.12109375  0.22363281 -0.17480469  0.03320312  0.09228516 -0.01287842
 -0.02856445  0.12890625  0.125      -0.01708984  0.07470703 -0.09228516
  0.02966309 -0.01928711 -0.04492188 -0.03173828  0.04467773 -0.08740234
  0.11376953  0.19335938  0.24804688 -0.20410156  0.0

In [35]:
len(vector1["person"])

300

In [36]:
len(vector1)

3000000

## similar words

In [37]:
print(vector1.most_similar("person"))

[('someone', 0.6657356023788452), ('persons', 0.5559711456298828), ('woman', 0.5470173358917236), ('somebody', 0.5459041595458984), ('peson', 0.5421414375305176), ('man', 0.5342026352882385), ('people', 0.5083409547805786), ('anyone', 0.5061744451522827), ('guy', 0.48752474784851074), ('Someone', 0.473005473613739)]


### king + women - men = ?

In [38]:
print(vector1.most_similar(positive=["king","women"],negative=["man"]))

[('queen', 0.4827326238155365), ('queens', 0.466781347990036), ('kumaris', 0.4653734564781189), ('kings', 0.4558638632297516), ('womens', 0.422832190990448), ('princes', 0.4176960587501526), ('Al_Anqari', 0.41725507378578186), ('concubines', 0.4011078476905823), ('monarch', 0.3962482810020447), ('monarchy', 0.39430150389671326)]


In [39]:
# similarity between words
print(vector1.similarity("men","women"))
print(vector1.similarity("men","car"))
print(vector1.similarity("men","boy"))
print(vector1.similarity("car","engine"))

# similarity between men and car is very less comapred to car<->engine and men<->human

0.7674937
0.12323477
0.32945722
0.4080042


In [40]:
import numpy as np
word1 = 'man'
word2 = 'woman'

word3 = 'semiconductor'
word4 = 'earthworm'

word5 = 'nephew'
word6 = 'niece'
vector_difference1 = model[word1] - model[word2]
vector_difference2 = model[word3] - model[word4]
vector_difference3 = model[word5] - model[word6]
magnitude_of_difference1 = np.linalg.norm(vector_difference1)
magnitude_of_difference2 = np.linalg.norm(vector_difference2)
magnitude_of_difference3 = np.linalg.norm(vector_difference3)

print("The magnitude of the difference between '{}' and '{}' is {:.2f}".format(word1, word2, magnitude_of_difference1))
print("The magnitude of the difference between '{}' and '{}' is {:.2f}".format(word3, word4, magnitude_of_difference2))
print("The magnitude of the difference between '{}' and '{}' is {:.2f}".format(word5, word6, magnitude_of_difference3))

The magnitude of the difference between 'man' and 'woman' is 1.73
The magnitude of the difference between 'semiconductor' and 'earthworm' is 5.67
The magnitude of the difference between 'nephew' and 'niece' is 1.96


# Creating token embedings

In [41]:
import torch

In [42]:
input_ids=torch.tensor([2,3,5,1])

In [43]:
vocab_size=6
output_dim=3
torch.manual_seed(123)
embeding_layer=torch.nn.Embedding(vocab_size,output_dim)

In [44]:
print(embeding_layer)

Embedding(6, 3)


In [45]:
print(embeding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


In [46]:
print(embeding_layer(torch.tensor([3])))

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)


In [47]:
print(embeding_layer(input_ids))

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)
